# **Matrix Operations**

In [1]:
import numpy

In [2]:
mat1 = numpy.array([[1, 3], [4, 6]])
mat2 = numpy.array([[7, 9], [11, 15]])
print ("Addition of  matrices ", mat1,",", mat2,"is")
print (numpy.add(mat1,mat2))

Addition of  matrices  [[1 3]
 [4 6]] , [[ 7  9]
 [11 15]] is
[[ 8 12]
 [15 21]]


In [3]:
print ("Subtraction of  matrices ", mat1,",", mat2,"is")
print (numpy.subtract(mat1,mat2))

Subtraction of  matrices  [[1 3]
 [4 6]] , [[ 7  9]
 [11 15]] is
[[-6 -6]
 [-7 -9]]


In [4]:
print ("Product of  matrices ", mat1,",", mat2,"is")
print (numpy.multiply(mat1,mat2))

Product of  matrices  [[1 3]
 [4 6]] , [[ 7  9]
 [11 15]] is
[[ 7 27]
 [44 90]]


In [5]:
print ("Dot Product of  matrices ", mat1,",", mat2,"is")
print (numpy.dot(mat1,mat2))

Dot Product of  matrices  [[1 3]
 [4 6]] , [[ 7  9]
 [11 15]] is
[[ 40  54]
 [ 94 126]]


In [6]:
print ("Division of  matrices ", mat1,",", mat2,"is")
print (numpy.divide(mat1,mat2))

Division of  matrices  [[1 3]
 [4 6]] , [[ 7  9]
 [11 15]] is
[[0.14285714 0.33333333]
 [0.36363636 0.4       ]]


In [7]:
print ("Transpose of ", mat1,"is")
print (mat1.T)

Transpose of  [[1 3]
 [4 6]] is
[[1 4]
 [3 6]]
