# **Semidefinite Programming with CVXPy**

In [1]:
import cvxpy as cvxp
import numpy as nump

<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject


In [2]:
n = 3
p = 3
nump.random.seed(1)
CMat = nump.random.randn(n, n)
AMat = []
bMat = []
for i in range(p):
    AMat.append(nump.random.randn(n, n))
    bMat.append(nump.random.randn())

In [3]:
XMat = cvxp.Variable((n,n), symmetric=True)

In [4]:
constraints = [XMat >> 0]
constraints += [
    cvxp.trace(AMat[i]@XMat) == bMat[i] for i in range(p)
]
problem = cvxp.Problem(cvxp.Minimize(cvxp.trace(CMat@XMat)),
                  constraints)
problem.solve()

2.654345662554787

In [5]:
print("The optimal value of the problem is", problem.value)
print("A solution X is")
print(XMat.value)

The optimal value of the problem is 2.654345662554787
A solution X is
[[ 1.6080543  -0.59770159 -0.69575807]
 [-0.59770159  0.22228515  0.24689083]
 [-0.69575807  0.24689083  1.39679094]]
