# **Tensor Operations**

In [1]:
from numpy import array
from numpy import tensordot

In [2]:
tensor1 = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[13,12,13], [14,15,16], [17,18,19]],
  [[24,22,23], [24,25,26], [27,28,29]],
  ])
tensor2 = array([
  [[1,4,3],    [4,5,6],    [7,8,9]],
  [[11,13,13], [14,15,16], [17,18,19]],
  [[21,25,23], [24,26,26], [27,28,29]],
  ])

In [3]:
print("tensor1",tensor1)
print("tensor2",tensor2)
print("sum of tensors", "is")
sum = tensor1 + tensor2
print(sum)

tensor1 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[13 12 13]
  [14 15 16]
  [17 18 19]]

 [[24 22 23]
  [24 25 26]
  [27 28 29]]]
tensor2 [[[ 1  4  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 13 13]
  [14 15 16]
  [17 18 19]]

 [[21 25 23]
  [24 26 26]
  [27 28 29]]]
sum of tensors is
[[[ 2  6  6]
  [ 8 10 12]
  [14 16 18]]

 [[24 25 26]
  [28 30 32]
  [34 36 38]]

 [[45 47 46]
  [48 51 52]
  [54 56 58]]]


In [5]:
print("difference of tensors",  "is")
diff = tensor1 - tensor2
print(diff)

difference of tensors is
[[[ 0 -2  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 2 -1  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 3 -3  0]
  [ 0 -1  0]
  [ 0  0  0]]]


In [6]:
print("product of tensors",  "is")
prod = tensor1 * tensor2
print(prod)

product of tensors is
[[[  1   8   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[143 156 169]
  [196 225 256]
  [289 324 361]]

 [[504 550 529]
  [576 650 676]
  [729 784 841]]]


In [7]:
print("division of tensors",  "is")
division = tensor1 / tensor2
print(division)

division of tensors is
[[[1.         0.5        1.        ]
  [1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[1.18181818 0.92307692 1.        ]
  [1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[1.14285714 0.88       1.        ]
  [1.         0.96153846 1.        ]
  [1.         1.         1.        ]]]


In [8]:
print("dot product of tensors",  "is")
dotproduct = tensordot(tensor1, tensor2, axes=0)
print(dotproduct)

dot product of tensors is
[[[[[[  1   4   3]
     [  4   5   6]
     [  7   8   9]]

    [[ 11  13  13]
     [ 14  15  16]
     [ 17  18  19]]

    [[ 21  25  23]
     [ 24  26  26]
     [ 27  28  29]]]


   [[[  2   8   6]
     [  8  10  12]
     [ 14  16  18]]

    [[ 22  26  26]
     [ 28  30  32]
     [ 34  36  38]]

    [[ 42  50  46]
     [ 48  52  52]
     [ 54  56  58]]]


   [[[  3  12   9]
     [ 12  15  18]
     [ 21  24  27]]

    [[ 33  39  39]
     [ 42  45  48]
     [ 51  54  57]]

    [[ 63  75  69]
     [ 72  78  78]
     [ 81  84  87]]]]



  [[[[  4  16  12]
     [ 16  20  24]
     [ 28  32  36]]

    [[ 44  52  52]
     [ 56  60  64]
     [ 68  72  76]]

    [[ 84 100  92]
     [ 96 104 104]
     [108 112 116]]]


   [[[  5  20  15]
     [ 20  25  30]
     [ 35  40  45]]

    [[ 55  65  65]
     [ 70  75  80]
     [ 85  90  95]]

    [[105 125 115]
     [120 130 130]
     [135 140 145]]]


   [[[  6  24  18]
     [ 24  30  36]
     [ 42  48  54]]

    [[ 66  78  78]