# **Vector Operations**

In [1]:
from numpy import array

In [2]:
vector1 = array([1, 2, 3])
vector2 = array([2, 3, 4])
print("dot product of", vector1,", ",vector2,"is")

product = vector1.dot(vector2)
print(product)

dot product of [1 2 3] ,  [2 3 4] is
20


In [3]:
scalarval = 0.3
scalarprod = scalarval*vector1
print("scalar multiplied",scalarval,",",vector1,"is")
print(scalarprod)

scalar multiplied 0.3 , [1 2 3] is
[0.3 0.6 0.9]


In [4]:
print("sum of", vector1,", ",vector2,"is")
sum = vector1 + vector2
print(sum)

sum of [1 2 3] ,  [2 3 4] is
[3 5 7]


In [5]:
print("difference of", vector1,", ",vector2,"is")
diff = vector1 - vector2
print(diff)

difference of [1 2 3] ,  [2 3 4] is
[-1 -1 -1]


In [6]:
print("product of", vector1,", ",vector2,"is")
prod = vector1 * vector2
print(prod)

product of [1 2 3] ,  [2 3 4] is
[ 2  6 12]


In [7]:
print("divison of", vector1,", ",vector2,"is")
dividedby = vector1 / vector2
print(dividedby)

divison of [1 2 3] ,  [2 3 4] is
[0.5        0.66666667 0.75      ]
